Repository hochschule-darmstadt/einander-helfen, pull requests merged in 2021-06, with the labels that each got.

#371 #364 fix No exact matching by country
  app/src/services/PostService.ts
Labels: bug, frontend

#378 #236 fix scrolled down post detail view
  app/src/components/posts/PostCard.vue
Labels: bug, frontend, high

#382 #365 fix location filter
  app/src/components/search/LocationSearchBar.vue
  app/src/components/search/SearchComponent.vue
  app/src/views/Posts.vue
Labels: bug, frontend, high

#386 Let CI fail on lint warnings
  app/package.json
  app/src/router.ts
  app/src/services/CountryService.ts
  app/src/services/PostService.ts
  app/src/store/Posts/index.ts
  app/src/store/Search/index.ts
  app/src/store/store.ts
  app/src/views/About.vue
Labels: enhancement, frontend

#388 Address package vulnerabilities
  app/package.json
Labels: enhancement, frontend

#392 Hotfix remove header spaces
  app/src/components/layout/MainHeader.vue
Labels: bug

#391 #389 fix the radius extended bug
  app/src/store/store.ts
Labels: bug, frontend, medium

#390 #372/reset page
  app/src/components/search/SearchComponent.vue
Labels: bug, frontend, medium

#384 #292 seperate image cards as own component
  app/src/components/layout/ImageCard.vue
  app/src/views/Home.vue
Labels: enhancement, frontend

#396 hotfix map list size bug
  app/src/views/Posts.vue
Labels: bug, frontend, high

#393 367/implement coding conventions
  app/src/App.vue
  app/src/components/layout/Carousel.vue
  app/src/components/layout/Footer.vue
  app/src/components/layout/MainHeader.vue
  app/src/components/layout/MenuButton.vue
  app/src/components/layout/ScrollTopButton.vue
  app/src/components/layout/SearchHeader.vue
  app/src/components/posts/MapButton.vue
  app/src/components/posts/MapCard.vue
  app/src/components/posts/PostCard.vue
  app/src/components/posts/PostListItem.vue
  app/src/components/posts/PostPagination.vue
  app/src/components/search/AreaSelect.vue
  app/src/components/search/LocationSearchBar.vue
  app/src/components/search/RadiusSelect.vue
  app/src/components/search/SearchBar.vue
  app/src/components/search/SearchButton.vue
  app/src/components/search/SearchComponent.vue
  app/src/router.ts
  app/src/services/CountryService.ts
  app/src/services/LocationService.ts
  app/src/services/PostService.ts
  app/src/services/TagService.ts
  app/src/store/Posts/index.ts
  app/src/store/Search/index.ts
  app/src/store/store.ts
  app/src/views/About.vue
  app/src/views/Home.vue
  app/src/views/Imprint.vue
  app/src/views/PageNotFound.vue
  app/src/views/Posts.vue
  app/src/views/Privacy.vue
Labels: enhancement, frontend, medium

#406 #271/use second index for elasticsearch upload
  etl/scripts/run_etl.sh
  etl/upload_to_elasticsearch/elastic.py
Labels: ETL, backend, enhancement, high, refactoring

#405 #387/scraper for sozialeinsatz.de
  app/src/views/About.vue
  etl/data_enhancement/enhance_data.py
  etl/data_enhancement/enhancement_location/lat_lon_enhancer.py
  etl/data_extraction/scraper/sozialeinsatz.py
Labels: ETL, backend, medium

#385 Add tracking
  .github/workflows/deployProduction.yml
  .github/workflows/deployStaging.yml
  .github/workflows/main.yml
  app/.env.production
  app/.env.staging
  app/package.json
  app/src/main.ts
  app/src/views/Privacy.vue
Labels: enhancement, frontend

#404 #336/loading state
  app/src/components/posts/PostListItemSkeleton.vue
  app/src/store/Posts/index.ts
  app/src/store/store.ts
  app/src/views/Posts.vue
Labels: enhancement, frontend

#394 337/additional volunteer work providers
  app/src/components/layout/Footer.vue
  app/src/components/layout/MenuButton.vue
  app/src/models/organization.ts
  app/src/resources/organizations/Organizations-einander-helfen.csv
  app/src/resources/organizations/index.js
  app/src/router.ts
  app/src/views/Organizations.vue
Labels: enhancement, frontend, medium

#408 #373 Added cleaning functionality for scraper text fields
  etl/data_extraction/Scraper.py
Labels: ETL, backend, enhancement

#411 #410/code cleanup and coding convention compliance
  etl/data_enhancement/enhance_data.py
  etl/data_enhancement/enhancement_duplicates/enhancement_exact_duplicates.py
  etl/data_enhancement/enhancement_duplicates/json_post.py
  etl/data_enhancement/enhancement_location/enhancement_location.py
  etl/data_enhancement/enhancement_location/lat_lon_enhancer.py
  etl/data_enhancement/enhancement_location/request_string_cleaner.py
  etl/data_enhancement/enhancement_tags/enhancement_tags.py
  etl/data_enhancement/enhancement_translation/enhancement_translation.py
  etl/data_extraction/scrape_data.py
  etl/data_extraction/scraper.py
  etl/data_extraction/scrapers/betterplace.py
  etl/data_extraction/scrapers/bundesfreiwilligendienst.py
  etl/data_extraction/scrapers/dksb_kinderschutzbund.py
  etl/data_extraction/scrapers/ehrenamt_hessen.py
  etl/data_extraction/scrapers/ehrenamt_sachsen.py
  etl/data_extraction/scrapers/ein_jahr_freiwillig.py
  etl/data_extraction/scrapers/european_youth_portal.py
  etl/data_extraction/scrapers/gutetat_berlin.py
  etl/data_extraction/scrapers/gutetat_hamburg.py
  etl/data_extraction/scrapers/gutetat_munich.py
  etl/data_extraction/scrapers/sozialeinsatz.py
  etl/data_extraction/scrapers/weltwaerts.py
  etl/data_management/data_manager.py
  etl/execute_elastic_upload.py
  etl/main.py
  etl/shared/logger_factory.py
  etl/shared/utils.py
  etl/test/test_data_enhancement/enhancement_location/__init__.py
  etl/test/test_data_enhancement/enhancement_location/test_lat_lon_enhancer.py
  etl/test/test_data_extraction/test_Scraper.py
  etl/test/test_data_management/test_DataManager.py
  etl/upload_to_elasticsearch/elastic.py
Labels: backend, documentation, enhancement

#409 Make map scrollable without ctrl on desktop
  app/src/components/posts/MapCard.vue
Labels: enhancement, frontend

#407 Use german osm data
  app/src/components/posts/MapCard.vue
Labels: enhancement, frontend

#376 #320/menu bug mobile
  app/src/components/layout/MenuButton.vue
Labels: enhancement, frontend

#403 #402 fix responsiveness of cards bug
  app/src/components/layout/ImageCards.vue
  app/src/views/Home.vue
Labels: bug, frontend, high

#413 398/improve 404 page not found page
  app/public/images/robot.png
  app/src/views/Imprint.vue
  app/src/views/Organizations.vue
  app/src/views/PageNotFound.vue
Labels: enhancement, frontend, medium

#416 add menu icon
  app/src/components/layout/MenuButton.vue
Labels: bug, frontend

#418 #399 implement custom scrollbar
  app/src/App.vue
  app/src/assets/styles/style.scss
  app/src/views/Posts.vue
Labels: enhancement, frontend

#419 #332 Change picture of carousel
  app/public/images/header/2.jpg
  app/public/images/header/2_phone.jpg
  app/public/images/header/backup/3.jpg
  app/src/views/Imprint.vue
Labels: enhancement, frontend, medium

#412 #395/sticky header
  app/src/components/layout/SearchHeader.vue
  app/src/components/search/SearchComponent.vue
  app/src/views/Posts.vue
Labels: enhancement, frontend
