Repository hochschule-darmstadt/einander-helfen, pull requests merged in 2021-11, with the labels that each got.

#470 #423 Avoidance of multiple parallel etl processes
  .gitignore
  etl/scripts/run_etl.sh
Labels: ETL, high, backend

#478 Remove pagination query from url for page 1
  app/src/store/store.ts
Labels: enhancement, frontend

#449 border-radius for boxed images on landing page
  app/src/components/layout/ImageCards.vue
Labels: good first issue, refactoring, frontend

#451 Devcontainer for FE
  app/.devcontainer/Dockerfile
  app/.devcontainer/devcontainer.json
  app/.prettierrc
  app/README.md
  app/package.json
  app/yarn.lock
Labels: documentation, refactoring, frontend

#462 Add backend devcontainer
  .gitignore
  etl/.devcontainer/Dockerfile
  etl/.devcontainer/devcontainer.json
Labels: enhancement, backend

#477 #459 add meta fragment for better crawling
  app/public/index.html
Labels: enhancement, frontend

#475 added alt atributes to all non decorative images
  app/src/components/layout/Carousel.vue
  app/src/components/search/AreaSelect.vue
Labels: enhancement, frontend

#484 #481 Context switch for german and american backend
  etl/README.md
  etl/data_enhancement/enhance_data.py
  etl/data_enhancement/enhancement_contexts/enhance_data_de.py
  etl/data_enhancement/enhancement_contexts/enhance_data_us.py
  etl/data_enhancement/enhancement_tags/enhancement_tags.py
  etl/data_extraction/scrape_data.py
  etl/data_extraction/scraper.py
  etl/data_extraction/scrapers/de/betterplace.py
  etl/data_extraction/scrapers/de/bundesfreiwilligendienst.py
  etl/data_extraction/scrapers/de/dksb_kinderschutzbund.py
  etl/data_extraction/scrapers/de/ehrenamt_hessen.py
  etl/data_extraction/scrapers/de/ehrenamt_sachsen.py
  etl/data_extraction/scrapers/de/ein_jahr_freiwillig.py
  etl/data_extraction/scrapers/de/european_youth_portal.py
  etl/data_extraction/scrapers/de/gutetat_berlin.py
  etl/data_extraction/scrapers/de/gutetat_hamburg.py
  etl/data_extraction/scrapers/de/gutetat_munich.py
  etl/data_extraction/scrapers/de/sozialeinsatz.py
  etl/data_extraction/scrapers/de/weltwaerts.py
  etl/data_management/data_manager.py
  etl/execute_elastic_upload.py
  etl/main.py
  etl/scripts/run_etl.sh
  etl/scripts/upload_to_elastic.sh
  etl/shared/utils.py
  etl/upload_to_elasticsearch/elastic.py
Labels: enhancement, ETL, high, backend

#479 #327 Limited popover width on map pins
  app/src/components/posts/MapCard.vue
Labels: bug, frontend
