Repository hochschule-darmstadt/einander-helfen, pull requests merged in 2021-12, with the labels that each got.

#488 Remove semantic relevant tags from not main content
  app/src/components/layout/MainHeader.vue
  app/src/components/posts/PostListItem.vue
Labels: enhancement, frontend

#450 landing page image carousel fix
  app/src/components/layout/Carousel.vue
Labels: good first issue, refactoring, frontend

#498 #485 added keywords to meta "description" and Meta "keywords"
  app/public/index.html
Labels: enhancement, frontend

#495 Open detailed post by clicking on a pin on mobile
  app/src/components/layout/SearchHeader.vue
  app/src/components/posts/MapCard.vue
  app/src/views/Posts.vue
Labels: enhancement, frontend

#493 #480 display 4 results from crawling in the boxes on the front page
  app/src/components/layout/ImageCard.vue
  app/src/components/layout/ImageCards.vue
  app/src/views/Home.vue
Labels: enhancement, frontend

#490 #486 Add US crawler for volunteermatch.org
  .gitignore
  etl/data_enhancement/de-Tags-einander-helfen.csv
  etl/data_enhancement/enhancement_contexts/enhance_data_us.py
  etl/data_enhancement/enhancement_location/lat_lon_enhancer.py
  etl/data_enhancement/enhancement_location/request_string_cleaner.py
  etl/data_enhancement/enhancement_tags/enhancement_tags.py
  etl/data_enhancement/us-Tags-einander-helfen.csv
  etl/data_extraction/scraper.py
  etl/data_extraction/scrapers/us/volunteermatch.py
Labels: ETL, high, backend

#506 Only show permanent markertext on mobile
  app/src/components/posts/MapCard.vue
Labels: enhancement, high, frontend

#496 Deployment to the new servers
  .github/workflows/deployProduction.yml
  .github/workflows/deployStaging.yml
  .github/workflows/main.yml
  .gitignore
  app/.devcontainer/Dockerfile
  app/.devcontainer/devcontainer.json
  app/.env.staging
  app/package.json
  app/yarn.lock
  etl/scripts/run_etl.sh
  etl/shared/utils.py
Labels: documentation, refactoring

#517 Add nebenan
  app/src/resources/organizations/Organizations-einander-helfen.csv
Labels: enhancement, frontend

#518 Add thousands point
  app/src/components/layout/MainHeader.vue
Labels: enhancement, frontend
