Repository hochschule-darmstadt/einander-helfen, pull requests merged in 2022-01, with the labels that each got.

#519 Add alt attributes to header icons
  app/src/components/layout/MainHeader.vue
Labels: enhancement, frontend

#520 Add canoncial tags with help from vue-meta
  app/package.json
  app/src/main.ts
  app/src/views/About.vue
  app/src/views/Home.vue
  app/src/views/Imprint.vue
  app/src/views/Organizations.vue
  app/src/views/PageNotFound.vue
  app/src/views/Posts.vue
  app/src/views/Privacy.vue
  app/yarn.lock
Labels: enhancement, refactoring, frontend

#523 #508 use Keywords in Title
  app/src/views/Home.vue
Labels: enhancement, frontend

#527 #285 Implemented enhance continents
  etl/data_enhancement/enhance_data.py
  etl/data_enhancement/enhancement_continents/enhancement_continents.py
  etl/data_extraction/scrapers/de/betterplace.py
  etl/data_extraction/scrapers/de/bundesfreiwilligendienst.py
  etl/data_extraction/scrapers/de/dksb_kinderschutzbund.py
  etl/data_extraction/scrapers/de/ehrenamt_hessen.py
  etl/data_extraction/scrapers/de/ehrenamt_sachsen.py
  etl/data_extraction/scrapers/de/ein_jahr_freiwillig.py
  etl/data_extraction/scrapers/de/european_youth_portal.py
  etl/data_extraction/scrapers/de/gutetat_berlin.py
  etl/data_extraction/scrapers/de/sozialeinsatz.py
  etl/data_extraction/scrapers/de/weltwaerts.py
  etl/data_extraction/scrapers/us/volunteermatch.py
  etl/requirements.txt
Labels: enhancement, medium, backend

#528 #452 plz over numpad not working
  app/src/components/search/LocationSearchBar.vue
Labels: bug, frontend

#521 Structure image cards
  app/src/components/layout/ImageCard.vue
  app/src/components/layout/ImageCards.vue
  app/src/locales/de.json
  app/src/locales/en.json
Labels: enhancement, frontend

#531 Set default env to de
  app/.env
Labels: high, frontend

#533 Fix typos
  app/src/components/search/SearchBar.vue
  app/src/components/search/SearchComponent.vue
Labels: refactoring

#538 Resolving merge conflicts from release before Christmas
  app/package.json
Labels: high
